/**
 * Plugin Loader — loads plugins and registers nodes into the in-memory registry.
 */

import * as fs from "fs";
import * as path from "path";
import { execSync } from "child_process";
import { pathToFileURL } from "url";
import { getNodeRegistry, getPluginNodeMap, deleteNode } from "../registry.js";
import { PACKAGES_PATH, MARKETPLACE_PATH, PLUGINS_DIR, NODES_HOME } from "../paths.js";

/**
 * Resolve a package directory's entry file from its package.json.
 *
 * CommonJS `require(dir)` reads package.json "main" and loads it; ESM `import(dir)`
 * does NOT do directory/main resolution for a filesystem path (it only does so for
 * bare package specifiers). Since the engine moved to ESM we resolve the entry
 * ourselves — supporting `exports["."]` and `main`, falling back to index.js.
 */
function resolveEntry(dir: string): string {
  // Unoverse runs under tsx in BOTH dev and prod (see Dockerfile), so it can import a
  // package's TypeScript source directly. For the in-Unoverse node packages (NODES_HOME),
  // prefer `src/index.ts` when it exists: this sidesteps the whole "stale/missing dist"
  // failure class — most painfully the `components` package, which is regenerated by
  // `nodegen:local` and whose gitignored dist silently goes missing (the runtime then
  // boots without those nodes and the workflow pulls a partial catalog → "Unknown node
  // type: CardFinder"). Loading from src also means a regenerated node takes effect on
  // restart with no separate build. Scoped to NODES_HOME so legacy /packages and
  // marketplace plugins keep their existing (bundled-dist) resolution untouched.
  if (path.resolve(dir).startsWith(path.resolve(NODES_HOME) + path.sep)) {
    const srcTs = path.join(dir, "src", "index.ts");
    if (fs.existsSync(srcTs)) return srcTs;
  }

  const pkg = JSON.parse(fs.readFileSync(path.join(dir, "package.json"), "utf-8"));
  let entry: string = pkg.main || "index.js";
  const exp = pkg.exports;
  if (exp) {
    const dot = typeof exp === "string" ? exp : exp["."] ?? exp;
    if (typeof dot === "string") entry = dot;
    else if (dot && typeof dot === "object") entry = dot.import || dot.require || dot.default || entry;
  }
  return path.join(dir, entry);
}

/**
 * Import a plugin from a directory (resolving its entry file as a file:// URL) or,
 * if no local directory exists, from its bare package specifier (npm-resolved).
 */
export async function importPluginModule(dirOrName: string): Promise<any> {
  let hasPkg = false;
  try {
    hasPkg = fs.existsSync(path.join(dirOrName, "package.json"));
  } catch {
    hasPkg = false;
  }
  // @vite-ignore: loading a plugin by name IS the job here, so the specifier cannot be
  // static. Vite is right to warn and there is nothing to fix while this folder exists;
  // the warning printed on every Studio start (see ./README.md, this folder is legacy).
  const target = hasPkg ? pathToFileURL(resolveEntry(dirOrName)).href : dirOrName;
  return import(/* @vite-ignore */ target);
}

/**
 * Clear all cached modules under a given path so re-import loads fresh code.
 *
 * Under ESM there is no `require.cache`, and `import()` caches by URL with no
 * public API to evict — so plugin hot-reload is a no-op here and is handled by
 * a process restart instead (see the marketplace upgrade docs). Guarded so the
 * call site stays identical to the CJS original.
 */
export function clearModuleCache(modulePath: string): void {
  const req = (globalThis as { require?: { cache?: Record<string, unknown> } }).require;
  if (!req?.cache) return;
  const resolved = path.resolve(modulePath);
  for (const key of Object.keys(req.cache)) {
    if (key.startsWith(resolved)) {
      delete req.cache[key];
    }
  }
}

export async function loadPlugin(pluginName: string, api: any): Promise<string[]> {
  const nodeRegistry = getNodeRegistry();
  const nodeTypes: string[] = [];
  const nodesBefore = new Set(nodeRegistry.keys());

  try {
    const shortName = pluginName.replace(/@[^/]+\//, "");
    // Resolution order: the in-Unoverse node home wins, then legacy /packages,
    // then /packages-marketplace, then the bare npm specifier.
    const homePath = path.join(NODES_HOME, shortName);
    const pkgPath = path.join(PACKAGES_PATH, shortName);
    const mktPath = path.join(MARKETPLACE_PATH, shortName);
    const resolvedPath = fs.existsSync(homePath)
      ? homePath
      : fs.existsSync(pkgPath)
        ? pkgPath
        : fs.existsSync(mktPath)
          ? mktPath
          : pluginName;

    const pkg = await importPluginModule(resolvedPath);
    const plugin = pkg.default || pkg;

    if (plugin && typeof plugin.setup === "function") {
      await plugin.setup(api);

      for (const [type] of nodeRegistry) {
        if (!nodesBefore.has(type)) {
          nodeTypes.push(type);
        }
      }

      // Stamp package-level marketplace metadata (package.json `gravity`) onto the nodes
      // this plugin just registered. By the authoring convention (docs-starter/nodes), a
      // package's icon lives in `gravity.logoUrl` and applies to every node in the package
      // — it is NOT repeated on each createNodeDefinition(). node-service merged this; the
      // Unoverse runtime didn't, so the Canvas drew these nodes with no icon. A node that
      // sets its own logoUrl wins; the package value is only a fallback.
      try {
        const pkgJsonPath = path.join(resolvedPath, "package.json");
        if (fs.existsSync(pkgJsonPath)) {
          const gravity = (JSON.parse(fs.readFileSync(pkgJsonPath, "utf-8")).gravity ?? {}) as {
            logoUrl?: string;
          };
          if (gravity.logoUrl) {
            for (const type of nodeTypes) {
              const def = nodeRegistry.get(type) as { logoUrl?: string } | undefined;
              if (def && !def.logoUrl) def.logoUrl = gravity.logoUrl;
            }
          }
        }
      } catch {
        // Marketplace metadata is best-effort — a missing/!malformed manifest must not
        // fail node loading.
      }
    }
  } catch (error: any) {
    console.log(`  ⚠ Failed to load ${pluginName}: ${error.message}`);
  }

  return nodeTypes;
}

export function unloadPlugin(pluginName: string): void {
  const pluginNodeMap = getPluginNodeMap();
  const nodeTypes = pluginNodeMap.get(pluginName) || [];

  // Drop from the in-memory registry. Workflow re-pulls the catalog (GET /nodes),
  // so there is no Redis catalog to purge.
  for (const nodeType of nodeTypes) {
    deleteNode(nodeType);
  }

  pluginNodeMap.delete(pluginName);
}

export function getPluginsDir(): string {
  return PLUGINS_DIR;
}

// The MINIMUM plugin-base the marketplace nodes need. The republished nodes call the
// 1.2.x API (hasPlatform/strict getPlatform), so an older copy in the plugins volume
// breaks every node that resolves it as a sibling. Keep in step with the version the
// unoverse app itself depends on (package.json — the baked copy).
const REQUIRED_PLUGIN_BASE = "1.2.5";

function versionAtLeast(installed: string, required: string): boolean {
  const a = installed.split(".").map(Number);
  const b = required.split(".").map(Number);
  for (let i = 0; i < 3; i++) {
    if ((a[i] ?? 0) > (b[i] ?? 0)) return true;
    if ((a[i] ?? 0) < (b[i] ?? 0)) return false;
  }
  return true;
}

export function ensurePluginsDir(): void {
  if (!fs.existsSync(PLUGINS_DIR)) {
    fs.mkdirSync(PLUGINS_DIR, { recursive: true });
  }
  const pkgJsonPath = path.join(PLUGINS_DIR, "package.json");
  if (!fs.existsSync(pkgJsonPath)) {
    fs.writeFileSync(pkgJsonPath, JSON.stringify({
      name: "gravity-plugins",
      private: true,
      dependencies: { "@unoverse-platform/plugin-base": `^${REQUIRED_PLUGIN_BASE}` },
    }, null, 2));
  }

  // Self-heal the volume's plugin-base: node reconciliation installs-if-missing and
  // never upgrades, so a volume seeded years ago keeps its original plugin-base
  // forever while freshly reconciled nodes assume the newer API. Upgrade in place
  // when the installed copy is older than the platform's minimum.
  const installedPkg = path.join(PLUGINS_DIR, "node_modules", "@unoverse-platform", "plugin-base", "package.json");
  let installedVersion: string | null = null;
  try {
    installedVersion = JSON.parse(fs.readFileSync(installedPkg, "utf8")).version ?? null;
  } catch {
    installedVersion = null; // not installed yet — startup's install pass seeds it
  }
  if (installedVersion && !versionAtLeast(installedVersion, REQUIRED_PLUGIN_BASE)) {
    console.log(`[plugins] plugin-base ${installedVersion} in the plugins volume is below the required ${REQUIRED_PLUGIN_BASE} — upgrading`);
    try {
      execSync(`npm install @unoverse-platform/plugin-base@^${REQUIRED_PLUGIN_BASE} --no-audit --no-fund`, {
        cwd: PLUGINS_DIR,
        stdio: "pipe",
      });
      console.log(`[plugins] plugin-base upgraded to ^${REQUIRED_PLUGIN_BASE}`);
    } catch (err) {
      console.error(`[plugins] plugin-base upgrade failed — marketplace nodes may not load:`, err instanceof Error ? err.message : err);
    }
  }
}
